### ISSUE TITLE
Does not work any more

### ISSUE THREAD

**Issue by hangcidu** [enric1994/arxiv.black#1]
It does not make the pdf itself to dark mode, or did I get it wrong?

**Comment by enric1994** [comment]
Hi @dutry, you are right. It doesn't really make the PDF dark mode but inverts the colours (for example,  images are transformed into its negatives).
You won't notice the dark mode if you download the PDF because arxiv.black only alters the CSS on the browser-based PDF viewer.

I tried it and everything is still working:
https://arxiv.org/pdf/1608.02395.pdf --> https://arxiv.black/pdf/1608.02395.pdf

You just have to replace `.org`  with `.black`

Hope it helps!

Enric

**Comment by hangcidu** [comment]
So, you put filter on the pdf webpage, but not any reverse color, right? (as follows)

<img width="1018" alt="Screen Shot 2022-04-09 at 3 55 18 AM" src="https://user-images.githubusercontent.com/17509207/162517524-eb1eb4be-bb65-4c87-b5fb-2bc2a531d917.png">

**Comment by enric1994** [comment]
Which browser are you using? I've never seen this before

**Comment by hangcidu** [comment]
I now know what is going on!

Because I turned on the Chrome Extension "Night Eye", which is incompatible with arxiv.black

Once I turn off the extension, everything works fine now.

Thank you for the site you developed
